apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/aegonish_blog"
            - name: PORT
              value: "4000"
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-google-credentials
                  key: client_id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-google-credentials
                  key: client_secret
            - name: GOOGLE_REDIRECT_URI
              value: "https://developers.google.com/oauthplayground"
            - name: GOOGLE_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-google-credentials
                  key: refresh_token
            - name: GOOGLE_DRIVE_FOLDER_ID
              value: "1c9O1S2u2ygET92zXpVEpHd_Y3yktCf8c"
          ports:
            - containerPort: {{ .Values.service.port }}


