apiVersion: v1
kind: Secret
metadata:
  name: backend-google-credentials
  namespace: aegonish
type: Opaque
stringData:
  client_id: ""
  client_secret: ""
  refresh_token: ""
  token.json: "{}" # kept for backward compatibility if needed, but unused by code
